### PR TITLE
Goal modification

### PR DESCRIPTION
**Pull request by nolife9face**

### CODE REVIEW

**Comment by nolife9face** [comment]
When you say more compact what do you mean? Less space between the goal and the title?

**Comment by Nitrofski** [comment]
Yes. Basically to make it feel more like it's part of the title area.

Also, I didn't check, but did you add the goal to the saved file? If so, make sure doing so does not break the file in the previous versions of WSplit. If it's not possible, we may want to consider changing to file format to add a version tag at the start for future, potentially file breaking changes.

The last part (about version tat) has low priority. It would be a "Nice to have" feature, more than anything. Wodanaz was not ambitious when he started the development of WSplit, making it very limited in the changes that can be made without refactoring a lot of code...

**Comment by nolife9face** [comment]
Yes I added the goal in the saved file. I tested the new file version with the version of wsplit without the goals. You can still open it without any problems but when you save, the goal field is erased.
I the new version of wsplit you can open old file without any problems adn when you save the goal field is inserted in the file.

I also took a look at livesplit import and there is a probleme now. You won't be able to import from wsplit if the file contain a goal... I have not looked at others timer.

**Comment by Nitrofski** [comment]
Ok, cool. The wonders of GitHub means it will be possible for us to just modify LiveSplit ourselves ;)

This is a tough one,  but I'm thinking we should modify the Llanfair import in WSplit to import goal as well. Normally, I should already read its size somewhere in the import algorithm to know how many bytes to skip... We would just need to read them instead ;p

**Comment by nolife9face** [comment]
So I made the title and the goal more compact but that is the best I can do for now... Making it better would need me to change values in like 5-6 differents place in the code. Obviously I will do a lot of refactoring to make the code more easy to change because I will have an hard time doing what I want to do without refactoring.

compactgoal

**Comment by nolife9face** [comment]
Yes modifing livesplit ourselves is the solution. 
For llanfair yes ill look into that.
Also the next thing I will work on it adding import from livesplit.
I will do some refactoring for that too...
When Im done with that I will probably do a lot of refactoring in the whole application.

**Comment by Nitrofski** [comment]
That's great! I'm glad somebody else picked this up :)

I was planning on doing the refactoring myself back then, but I got tok busy. I started some with the painting logic, but didn't quite go as far as I wanted with that...

**Comment by nolife9face** [comment]
I looked at llanfair import and it seems that the only thing that was missing was to add the strGoal into the text box. The goal is read from the file... I tested it and it works.

**Comment by Nitrofski** [comment]
Nice.

Is this ready to be merged or did you want to work a bit more into it?

**Comment by nolife9face** [comment]
Yes you can merge it.

Thanks.

**Pull request merged**
